export const Queries = {
  timelines: {
    home: {
      queryId: 'r_h-5lnRVmgooGgRomqn8A',
      operationName: 'HomeTimeline',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
    following: {
      queryId: '6lNc8BMVpQCnBCbHmVWRLw',
      operationName: 'HomeLatestTimeline',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
    list: {
      queryId: 'KQJrm_e6Y--VArbruBzzAw',
      operationName: 'ListLatestTweetsTimeline',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
    posts: {
      queryId: 'fafowSZBCQYf5-CNIZ04bw',
      operationName: 'UserTweets',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
    media: {
      queryId: 'IomGDb0O4Qjp0JHe27clDg',
      operationName: 'UserMedia',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
    replies: {
      queryId: 'bAO1gMk6B7iDoOp2sDCDyw',
      operationName: 'UserTweetsAndReplies',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
    tweetReplies: {
      queryId: '5IxZ_DFOXCqILZ1LK_3tdA',
      operationName: 'TweetDetail',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
    search: {
      queryId: 's2_tz3AV4J9EJAmAkde_SA',
      operationName: 'SearchTimeline',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
    notifications: {
      queryId: 'HnZ0x_pQeDaqvrZ9hdm0Wg',
      operationName: 'NotificationsTimeline',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'rweb_video_screen_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'premium_content_api_read_enabled',
          'communities_web_enable_tweet_community_results_fetch',
          'c9s_tweet_anatomy_moderator_badge_enabled',
          'responsive_web_grok_analyze_button_fetch_trends_enabled',
          'responsive_web_grok_analyze_post_followups_enabled',
          'responsive_web_jetfuel_frame',
          'responsive_web_grok_share_attachment_enabled',
          'articles_preview_enabled',
          'responsive_web_edit_tweet_api_enabled',
          'graphql_is_translatable_rweb_tweet_is_translatable_enabled',
          'view_counts_everywhere_api_enabled',
          'longform_notetweets_consumption_enabled',
          'responsive_web_twitter_article_tweet_consumption_enabled',
          'tweet_awards_web_tipping_enabled',
          'responsive_web_grok_show_grok_translated_post',
          'responsive_web_grok_analysis_button_from_backend',
          'creator_subscriptions_quote_tweet_preview_enabled',
          'freedom_of_speech_not_reach_fetch_enabled',
          'standardized_nudges_misinfo',
          'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled',
          'longform_notetweets_rich_text_read_enabled',
          'longform_notetweets_inline_media_enabled',
          'responsive_web_grok_image_annotation_enabled',
          'responsive_web_grok_imagine_annotation_enabled',
          'responsive_web_grok_community_note_auto_translation_is_enabled',
          'responsive_web_enhance_cards_enabled',
        ],
        fieldToggles: [
          'withAuxiliaryUserLabels',
          'withArticleRichContentState',
          'withArticlePlainText',
          'withGrokAnalyze',
          'withDisallowedReplyControls',
        ],
      },
    },
  },
  profiles: {
    byScreenName: {
      queryId: 'Ww3msXHEuukH8UdL-GXJDg',
      operationName: 'UserByScreenName',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'hidden_profile_subscriptions_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'subscriptions_verification_info_is_identity_verified_enabled',
          'subscriptions_verification_info_verified_since_enabled',
          'highlights_tweets_tab_ui_enabled',
          'responsive_web_twitter_article_notes_tab_enabled',
          'subscriptions_feature_can_gift_premium',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
        ],
        fieldToggles: ['withAuxiliaryUserLabels'],
      },
    },
    byRestId: {
      queryId: '1WTI473d0DEs__f1fPw4YQ',
      operationName: 'UserByRestId',
      operationType: 'query',
      metadata: {
        featureSwitches: [
          'hidden_profile_subscriptions_enabled',
          'payments_enabled',
          'profile_label_improvements_pcf_label_in_post_enabled',
          'responsive_web_profile_redirect_enabled',
          'rweb_tipjar_consumption_enabled',
          'verified_phone_label_enabled',
          'highlights_tweets_tab_ui_enabled',
          'responsive_web_twitter_article_notes_tab_enabled',
          'subscriptions_feature_can_gift_premium',
          'creator_subscriptions_tweet_preview_api_enabled',
          'responsive_web_graphql_skip_user_profile_image_extensions_enabled',
          'responsive_web_graphql_timeline_navigation_enabled',
        ],
        fieldToggles: ['withAuxiliaryUserLabels'],
      },
    },
  },
};

export type Queries =
  | (typeof Queries.profiles)[keyof typeof Queries.profiles]
  | (typeof Queries.timelines)[keyof typeof Queries.timelines];
